server:
  port: 9090

spring:
  application:
    name: admin-server

management:
  metrics:
    tags:
      application: ${spring.application.name}

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
