spring:
  application:
    name: customer-service

management:
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server:
          requests: true
      slo:
        http:
          server:
            requests: 50ms, 100ms, 200ms, 400ms
      percentiles:
        http:
          server:
            requests: 0.5, 0.9, 0.95, 0.99, 0.999

---
﻿spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://zipkin:9411
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    metadataMap:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
